### ISSUE TITLE
Advertised to not need root access. Errors out.

### ISSUE THREAD

**Issue by Mirppc** [aario/MyWifiPasswords#2]
Installed the program because it said root access was not needed on the fdroid page. It errors out saying "Error: can't get root access"

Fdroid 1.0.4
Motorola g4

**Comment by Mirppc** [comment]
https://imgur.com/a/vFnoLyG
https://imgur.com/a/XM0DvQa

**Comment by aario** [comment]
Thanks for reporting the issue.  Actually on the README of the project it is mentioned that the app needs root:
https://github.com/aario/MyWifiPasswords/blob/master/README.md
Then again on the request to F-Droid to include the app it was mentioned again:
https://gitlab.com/fdroid/rfp/issues/836
So please file the same issue on F-Droid issue tracker instead.
